VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CalendarNode"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public PrevNode As CalendarNode     'Previous history entry
Public NextNode As CalendarNode     'Next history entry

Public GameDate As Date             'Date of Game
Public Time As String               'Time
Public Place As String              'Place
Public Notes As String              'Notes
